In [16]:
import numpy as np
matrix1=np.array([[2,4,1],[5,3,2],[1,6,7]])
matrix2=np.array([[5,3,1],[0,2,5],[1,6,4]])

In [9]:
matrix1

array([[2, 4, 1],
       [5, 3, 2],
       [1, 6, 7]])

In [10]:
matrix2

array([[5, 3, 1],
       [0, 2, 5],
       [1, 6, 4]])

In [11]:
sum=matrix1+matrix2
sum

array([[ 7,  7,  2],
       [ 5,  5,  7],
       [ 2, 12, 11]])

In [12]:
mult=matrix1*matrix2
mult

array([[10, 12,  1],
       [ 0,  6, 10],
       [ 1, 36, 28]])

In [14]:
div=matrix2/matrix1
div

array([[2.5       , 0.75      , 1.        ],
       [0.        , 0.66666667, 2.5       ],
       [1.        , 1.        , 0.57142857]])

In [15]:
subtract=matrix2-matrix1
subtract

array([[ 3, -1,  0],
       [-5, -1,  3],
       [ 0,  0, -3]])

In [17]:
np.sqrt(matrix1)

array([[1.41421356, 2.        , 1.        ],
       [2.23606798, 1.73205081, 1.41421356],
       [1.        , 2.44948974, 2.64575131]])

In [18]:
np.sqrt(matrix2)

array([[2.23606798, 1.73205081, 1.        ],
       [0.        , 1.41421356, 2.23606798],
       [1.        , 2.44948974, 2.        ]])

In [20]:
matrix1.min()

1

In [21]:
matrix2.min()

0

In [22]:
matrix1.max()

7

In [23]:
matrix2.max()

6

In [25]:
matrix1

array([[2, 4, 1],
       [5, 3, 2],
       [1, 6, 7]])

In [27]:
np.where(matrix1>5)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [28]:
# size on a memory in bits
import sys
matrix1.itemsize    

4

In [29]:
matrix2.itemsize

4

In [30]:
size=matrix1.itemsize * matrix2.itemsize
size

16